# encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# users = User.create([ {:name => 'Mikko', :email => 'moi@iki.fi', :password }])

sports = Sport.create([ {:name => 'Ammunta'},
                        {:name => 'Jalkapallo'},
                        {:name => 'Jousiammunta'},
                        {:name => 'Judo'},
                        {:name => 'Koripallo'},
                        {:name => 'Käsipallo'},
                        {:name => 'Lentopallo'},
                        {:name => 'Maahockey'},
                        {:name => 'Melonta'},
                        {:name => 'Miekkailu'},
                        {:name => 'Nykyaikainen viisiottelu'},
                        {:name => 'Nyrkkeily'},
                        {:name => 'Paini'},
                        {:name => 'Painonnosto'},
                        {:name => 'Purjehdus'},
                        {:name => 'Pyöräily'},
                        {:name => 'Pöytätennis'},
                        {:name => 'Ratsastus'},
                        {:name => 'Soutu'},
                        {:name => 'Sulkapallo'},
                        {:name => 'Taekwondo'},
                        {:name => 'Taitouinti'},
                        {:name => 'Tennis'},
                        {:name => 'Triathlon'},
                        {:name => 'Uimahypyt'},
                        {:name => 'Uinti'},
                        {:name => 'Vesipallo'},
                        {:name => 'Voimistelu'},
                        {:name => 'Yleisurheilu'}
                      ])

events = Event.create([ {:name => 'Jalkapallo', :sport => Sport.find(2), :series => 1},
                        {:name => 'Jalkapallo', :sport => Sport.find(2), :series => 2},
                        {:name => '50m Pienoiskiväärin moniasentokilpailu', :sport => Sport.find(1), :series => 1},
                        {:name => '50m Pienoiskiväärin makuukilpailu', :sport => Sport.find(1), :series => 1},
                        {:name => '10m Ilmakivääri', :sport => Sport.find(1), :series => 1},
                        {:name => '50m Pistooli', :sport => Sport.find(1), :series => 1},
                        {:name => '25m Olympiapistooli', :sport => Sport.find(1), :series => 1},
                        {:name => '10m Ilmapistooli', :sport => Sport.find(1), :series => 1},
                        {:name => 'Trap', :sport => Sport.find(1), :series => 1},
                        {:name => 'Kaksois-trap', :sport => Sport.find(1), :series => 1},
                        {:name => 'Skeet', :sport => Sport.find(1), :series => 1},
                        {:name => '50m Pienoiskiväärin moniasentokilpailu', :sport => Sport.find(1), :series => 2},
                        {:name => '10m Ilmakivääri', :sport => Sport.find(1), :series => 2},
                        {:name => '25m Olympiapistooli', :sport => Sport.find(1), :series => 2},
                        {:name => '10m Ilmapistooli', :sport => Sport.find(1), :series => 2},
                        {:name => 'Trap', :sport => Sport.find(1), :series => 2},
                        {:name => 'Skeet', :sport => Sport.find(1), :series => 2},
                        {:name => 'Jousiammunta', :sport => Sport.find(3), :series => 1},
                        {:name => 'Joukkuekilpailu', :sport => Sport.find(3), :series => 1},
                        {:name => 'Jousiammunta', :sport => Sport.find(3), :series => 2},
                        {:name => 'Joukkuekilpailu', :sport => Sport.find(3), :series => 2},
                        {:name => '-60kg', :sport => Sport.find(4), :series => 1},
                        {:name => '60-66kg', :sport => Sport.find(4), :series => 1},
                        {:name => '66-73kg', :sport => Sport.find(4), :series => 1},
                        {:name => '73-81kg', :sport => Sport.find(4), :series => 1},
                        {:name => '81-90kg', :sport => Sport.find(4), :series => 1},
                        {:name => '90-100kg', :sport => Sport.find(4), :series => 1},
                        {:name => '+100kg', :sport => Sport.find(4), :series => 1},
                        {:name => '-48kg', :sport => Sport.find(4), :series => 2},
                        {:name => '48-52kg', :sport => Sport.find(4), :series => 2},
                        {:name => '52-57kg', :sport => Sport.find(4), :series => 2},
                        {:name => '57-63kg', :sport => Sport.find(4), :series => 2},
                        {:name => '63-70kg', :sport => Sport.find(4), :series => 2},
                        {:name => '70-78kg', :sport => Sport.find(4), :series => 2},
                        {:name => '+78kg', :sport => Sport.find(4), :series => 2},
                        {:name => 'Koripallo', :sport => Sport.find(5), :series => 1},
                        {:name => 'Koripallo', :sport => Sport.find(5), :series => 2},
                        {:name => 'Käsipallo', :sport => Sport.find(6), :series => 1},
                        {:name => 'Käsipallo', :sport => Sport.find(6), :series => 2},
                        {:name => 'Lentopallo', :sport => Sport.find(7), :series => 1},
                        {:name => 'Lentopallo', :sport => Sport.find(7), :series => 2},
                        {:name => 'Rantalentopallo', :sport => Sport.find(7), :series => 1},
                        {:name => 'Rantalentopallo', :sport => Sport.find(7), :series => 2},
                        {:name => 'Maahockey', :sport => Sport.find(8), :series => 1},
                        {:name => 'Maahockey', :sport => Sport.find(8), :series => 2},
                        {:name => '500m Kanadalaisyksikkö', :sport => Sport.find(9), :series => 1},
                        {:name => '500m Kanadalaiskaksikko', :sport => Sport.find(9), :series => 1},
                        {:name => '500m Kajakkiyksikkö', :sport => Sport.find(9), :series => 1},
                        {:name => '1000m Kanadalaisyksikkö', :sport => Sport.find(9), :series => 1},
                        {:name => '1000m Kanadalaiskaksikko', :sport => Sport.find(9), :series => 1},
                        {:name => '1000m Kajakkiyksikkö', :sport => Sport.find(9), :series => 1},
                        {:name => '500m Kajakkikaksikko', :sport => Sport.find(9), :series => 1},
                        {:name => '1000m Kajakkikaksikko', :sport => Sport.find(9), :series => 1},
                        {:name => '1000m Kajakkinelikko', :sport => Sport.find(9), :series => 1},
                        {:name => 'Koskimelonta Kanadalaisyksikkö', :sport => Sport.find(9), :series => 1},
                        {:name => 'Koskimelonta Kanadalaiskaksikko', :sport => Sport.find(9), :series => 1},
                        {:name => 'Koskimelonta Kajakkiyksikkö', :sport => Sport.find(9), :series => 1},
                        {:name => '500m Kajakkiyksikkö', :sport => Sport.find(9), :series => 2},
                        {:name => '500m Kajakkikaksikko', :sport => Sport.find(9), :series => 2},
                        {:name => '500m Kajakkinelikko', :sport => Sport.find(9), :series => 2},
                        {:name => 'Koskimelonta Kajakkiyksikkö', :sport => Sport.find(9), :series => 2},
                        {:name => 'Floretti', :sport => Sport.find(10), :series => 1},
                        {:name => 'Kalpa', :sport => Sport.find(10), :series => 1},
                        {:name => 'Floretin joukkuekilpailu', :sport => Sport.find(10), :series => 1},
                        {:name => 'Säilä', :sport => Sport.find(10), :series => 1},
                        {:name => 'Säilän joukkuekilpailu', :sport => Sport.find(10), :series => 1},
                        {:name => 'Floretti', :sport => Sport.find(10), :series => 2},
                        {:name => 'Floretin joukkuekilpailu', :sport => Sport.find(10), :series => 2},
                        {:name => 'Säilä', :sport => Sport.find(10), :series => 2},
                        {:name => 'Kalpan joukkuekilpailu', :sport => Sport.find(10), :series => 2},
                        {:name => 'Kalpa', :sport => Sport.find(10), :series => 2},
                        {:name => 'Nykyaikainen viisiottelu', :sport => Sport.find(11), :series => 1},
                        {:name => 'Nykyaikainen viisiottelu', :sport => Sport.find(11), :series => 2},
                        {:name => 'Kevyt kärpässarja (-49kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Kärpässarja (49-52kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Kääpiösarja (52-56kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Kevytsarja (56-60kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Kevyt välisarja (60-64kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Välisarja (64-69kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Keskisarja (69-75kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Raskas keskisarja (75-81kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Raskassarja (81-91kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Superraskassarja (+91kg)', :sport => Sport.find(12), :series => 1},
                        {:name => 'Kärpässarja (-51kg)', :sport => Sport.find(12), :series => 2},
                        {:name => 'Kevytsarja (51-60kg)', :sport => Sport.find(12), :series => 2},
                        {:name => 'Keskisarja (60-75kg)', :sport => Sport.find(12), :series => 2},
                        {:name => 'Kreikkalais-Roomalainen kääpiösarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Kreikkalais-Roomalainen höyhensarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Kreikkalais-Roomalainen kevytsarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Kreikkalais-Roomalainen välisarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Kreikkalais-Roomalainen keskisarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Kreikkalais-Roomalainen raskasarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Kreikkalais-Roomalainen super raskassarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini kääpiösarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini höyhensarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini kevytsarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini välisarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini keskisarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini raskassarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini super raskassarja', :sport => Sport.find(13), :series => 1},
                        {:name => 'Vapaapaini kärpässarja', :sport => Sport.find(13), :series => 2},
                        {:name => 'Vapaapaini kevytsarja', :sport => Sport.find(13), :series => 2},
                        {:name => 'Vapaapaini keskisarja', :sport => Sport.find(13), :series => 2},
                        {:name => 'Vapaapaini raskassarja', :sport => Sport.find(13), :series => 2},
                        {:name => '56kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '62kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '69kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '77kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '85kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '94kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '105kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '+105kg painonnosto', :sport => Sport.find(14), :series => 1},
                        {:name => '48kg painonnosto', :sport => Sport.find(14), :series => 2},
                        {:name => '53kg painonnosto', :sport => Sport.find(14), :series => 2},
                        {:name => '58kg painonnosto', :sport => Sport.find(14), :series => 2},
                        {:name => '63kg painonnosto', :sport => Sport.find(14), :series => 2},
                        {:name => '69kg painonnosto', :sport => Sport.find(14), :series => 2},
                        {:name => '75kg painonnosto', :sport => Sport.find(14), :series => 2},
                        {:name => '+75kg painonnosto', :sport => Sport.find(14), :series => 2},
                        {:name => 'Laser', :sport => Sport.find(15), :series => 1},
                        {:name => 'Finnjolla', :sport => Sport.find(15), :series => 1},
                        {:name => '470', :sport => Sport.find(15), :series => 1},
                        {:name => '49er', :sport => Sport.find(15), :series => 1},
                        {:name => 'Purjelauta (RS:X)', :sport => Sport.find(15), :series => 1},
                        {:name => 'Star', :sport => Sport.find(15), :series => 1},
                        {:name => 'Laser radial ', :sport => Sport.find(15), :series => 2},
                        {:name => '470', :sport => Sport.find(15), :series => 2},
                        {:name => 'Elliot 6m', :sport => Sport.find(15), :series => 2},
                        {:name => 'Purjelauta (RS:X)', :sport => Sport.find(15), :series => 2},
                        {:name => 'BMX-pyöräily', :sport => Sport.find(16), :series => 1},
                        {:name => 'BMX-pyöräily', :sport => Sport.find(16), :series => 2},
                        {:name => 'Maantieajo', :sport => Sport.find(16), :series => 1},
                        {:name => 'Maantiepyöräily aika-ajo', :sport => Sport.find(16), :series => 1},
                        {:name => 'Maantieajo', :sport => Sport.find(16), :series => 2},
                        {:name => 'Maantiepyöräily aika-ajo', :sport => Sport.find(16), :series => 2},
                        {:name => 'Maastopyöräily', :sport => Sport.find(16), :series => 1},
                        {:name => 'Maastopyöräily', :sport => Sport.find(16), :series => 2},
                        {:name => 'Ratapyöräily Sprintti', :sport => Sport.find(16), :series => 1},
                        {:name => 'Ratapyöräily Joukkueajo', :sport => Sport.find(16), :series => 1},
                        {:name => 'Ratapyöräily Keirin', :sport => Sport.find(16), :series => 1},
                        {:name => 'Ratapyöräily Omnium', :sport => Sport.find(16), :series => 1},
                        {:name => 'Ratapyöräily Joukkuetakaa-ajo', :sport => Sport.find(16), :series => 1},
                        {:name => 'Ratapyöräily Sprintti', :sport => Sport.find(16), :series => 2},
                        {:name => 'Ratapyöräily Joukkueajo', :sport => Sport.find(16), :series => 2},
                        {:name => 'Ratapyöräily Keirin', :sport => Sport.find(16), :series => 2},
                        {:name => 'Ratapyöräily Omnium', :sport => Sport.find(16), :series => 2},
                        {:name => 'Ratapyöräily Joukkuetakaa-ajo', :sport => Sport.find(16), :series => 2},
                        {:name => 'Yksinpeli', :sport => Sport.find(17), :series => 1},
                        {:name => 'Kaksinpeli', :sport => Sport.find(17), :series => 1},
                        {:name => 'Yksinpeli', :sport => Sport.find(17), :series => 2},
                        {:name => 'Kaksinpeli', :sport => Sport.find(17), :series => 2},
                        {:name => 'Kouluratsastus ', :sport => Sport.find(18), :series => 3},
                        {:name => 'Kouluratsastus, Joukkue', :sport => Sport.find(18), :series => 3},
                        {:name => 'Esteratsastus', :sport => Sport.find(18), :series => 3},
                        {:name => 'Esteratsastus, joukkue', :sport => Sport.find(18), :series => 3},
                        {:name => 'Kenttäratsastus', :sport => Sport.find(18), :series => 3},
                        {:name => 'Kenttäratsastus, joukkue', :sport => Sport.find(18), :series => 3},
                        {:name => 'Yksikkö', :sport => Sport.find(19), :series => 1},
                        {:name => 'Pariairokaksikko', :sport => Sport.find(19), :series => 1},
                        {:name => 'Pariaironelikko', :sport => Sport.find(19), :series => 1},
                        {:name => 'Perämiehetön kaksikko', :sport => Sport.find(19), :series => 1},
                        {:name => 'Perämiehetön nelikko', :sport => Sport.find(19), :series => 1},
                        {:name => 'Kahdeksikko', :sport => Sport.find(19), :series => 1},
                        {:name => 'Kevyt pariairokaksikko', :sport => Sport.find(19), :series => 1},
                        {:name => 'Kevyt pariaironelikko', :sport => Sport.find(19), :series => 1},
                        {:name => 'Pariairokaksikko', :sport => Sport.find(19), :series => 2},
                        {:name => 'Pariaironelikko', :sport => Sport.find(19), :series => 2},
                        {:name => 'Perämiehetön kaksikko', :sport => Sport.find(19), :series => 2},
                        {:name => 'Kevyt pariairokaksikko', :sport => Sport.find(19), :series => 2},
                        {:name => 'Kahdeksikko', :sport => Sport.find(19), :series => 2},
                        {:name => 'Yksikkö', :sport => Sport.find(19), :series => 2},
                        {:name => 'Yksinpeli', :sport => Sport.find(20), :series => 1},
                        {:name => 'Kaksinpeli', :sport => Sport.find(20), :series => 1},
                        {:name => 'Yksinpeli', :sport => Sport.find(20), :series => 2},
                        {:name => 'Kaksinpeli', :sport => Sport.find(20), :series => 2},
                        {:name => 'Kaksinpeli', :sport => Sport.find(20), :series => 3},
                        {:name => '+80kg taekwondo', :sport => Sport.find(21), :series => 1},
                        {:name => '-58kg taekwondo', :sport => Sport.find(21), :series => 1},
                        {:name => '58-68kg taekwondo', :sport => Sport.find(21), :series => 1},
                        {:name => '68-80kg taekwondo', :sport => Sport.find(21), :series => 1},
                        {:name => '+67kg taekwondo', :sport => Sport.find(21), :series => 2},
                        {:name => '-49kg taekwondo', :sport => Sport.find(21), :series => 2},
                        {:name => '49-57kg taekwondo', :sport => Sport.find(21), :series => 2},
                        {:name => '57-67kg taekwondo', :sport => Sport.find(21), :series => 2},
                        {:name => 'Yksinpeli', :sport => Sport.find(23), :series => 1},
                        {:name => 'Kaksinpeli', :sport => Sport.find(23), :series => 1},
                        {:name => 'Yksinpeli', :sport => Sport.find(23), :series => 2},
                        {:name => 'Kaksinpeli', :sport => Sport.find(23), :series => 2},
                        {:name => 'Parikilpailu', :sport => Sport.find(22), :series => 2},
                        {:name => 'Joukkuekilpailu', :sport => Sport.find(22), :series => 2},
                        {:name => 'Triathlon', :sport => Sport.find(24), :series => 1},
                        {:name => 'Triathlon', :sport => Sport.find(24), :series => 2},
                        {:name => '10m Kerroshypyt', :sport => Sport.find(25), :series => 1},
                        {:name => '3m Ponnahduslauta', :sport => Sport.find(25), :series => 1},
                        {:name => '10m pari kerroshypyt', :sport => Sport.find(25), :series => 1},
                        {:name => '3m pari ponnahduslautahypyt', :sport => Sport.find(25), :series => 1},
                        {:name => '10m Kerroshypyt', :sport => Sport.find(25), :series => 2},
                        {:name => '3m Ponnahduslauta', :sport => Sport.find(25), :series => 2},
                        {:name => '3m pari ponnahduslautahypyt', :sport => Sport.find(25), :series => 2},
                        {:name => '10m pari kerroshypyt', :sport => Sport.find(25), :series => 2},
                        {:name => '50m vapaauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '100m vapaauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '200m vapaauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '400m vapaauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '1500m vapaauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '100m selkäuinti', :sport => Sport.find(26), :series => 1},
                        {:name => '200m selkäuinti', :sport => Sport.find(26), :series => 1},
                        {:name => '100m rintauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '200m rintauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '100m perhosuinti', :sport => Sport.find(26), :series => 1},
                        {:name => '200m perhosuinti', :sport => Sport.find(26), :series => 1},
                        {:name => '200m sekauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '400m sekauinti', :sport => Sport.find(26), :series => 1},
                        {:name => '4x100m vapaauintiviesti', :sport => Sport.find(26), :series => 1},
                        {:name => '4x200m vapaauintiviesti', :sport => Sport.find(26), :series => 1},
                        {:name => '4x100m sekauintiviesti', :sport => Sport.find(26), :series => 1},
                        {:name => '10 000m avovesiuinti', :sport => Sport.find(26), :series => 1},
                        {:name => '50m vapaauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '100m vapaauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '200m vapaauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '400m vapaauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '800m vapaauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '100m selkäuinti', :sport => Sport.find(26), :series => 2},
                        {:name => '200m selkäuinti', :sport => Sport.find(26), :series => 2},
                        {:name => '100m rintauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '200m rintauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '100m perhosuinti', :sport => Sport.find(26), :series => 2},
                        {:name => '200m perhosuinti', :sport => Sport.find(26), :series => 2},
                        {:name => '200m sekauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '400m sekauinti', :sport => Sport.find(26), :series => 2},
                        {:name => '4x100 vapaauintiviesti', :sport => Sport.find(26), :series => 2},
                        {:name => '4x200m vapaauintiviesti', :sport => Sport.find(26), :series => 2},
                        {:name => '4x100m sekauintiviesti', :sport => Sport.find(26), :series => 2},
                        {:name => '10 000m avovesiuinti', :sport => Sport.find(26), :series => 2},
                        {:name => 'Vesipallo', :sport => Sport.find(27), :series => 1},
                        {:name => 'Vesipallo', :sport => Sport.find(27), :series => 2},
                        {:name => 'Rytminen voimistelu, joukkue', :sport => Sport.find(28), :series => 2},
                        {:name => 'Rytminen voimistelu', :sport => Sport.find(28), :series => 2},
                        {:name => 'Permanto', :sport => Sport.find(28), :series => 1},
                        {:name => 'Rekki', :sport => Sport.find(28), :series => 1},
                        {:name => 'Hypyt', :sport => Sport.find(28), :series => 1},
                        {:name => 'Nojapuut', :sport => Sport.find(28), :series => 1},
                        {:name => 'Hevonen', :sport => Sport.find(28), :series => 1},
                        {:name => 'Renkaat', :sport => Sport.find(28), :series => 1},
                        {:name => 'Moniottelu', :sport => Sport.find(28), :series => 1},
                        {:name => 'Joukkuekilpailu', :sport => Sport.find(28), :series => 1},
                        {:name => 'Hypyt', :sport => Sport.find(28), :series => 2},
                        {:name => 'Nojapuut/rekki', :sport => Sport.find(28), :series => 2},
                        {:name => 'Puomi', :sport => Sport.find(28), :series => 2},
                        {:name => 'Permanto', :sport => Sport.find(28), :series => 2},
                        {:name => 'Moniottelu', :sport => Sport.find(28), :series => 2},
                        {:name => 'Joukkuekilpailu', :sport => Sport.find(28), :series => 2},
                        {:name => '10 000m', :sport => Sport.find(29), :series => 1},
                        {:name => '100m', :sport => Sport.find(29), :series => 1},
                        {:name => '110m aidat', :sport => Sport.find(29), :series => 1},
                        {:name => '1500m', :sport => Sport.find(29), :series => 1},
                        {:name => '200m', :sport => Sport.find(29), :series => 1},
                        {:name => '20km kävely', :sport => Sport.find(29), :series => 1},
                        {:name => '3000m estejuoksu', :sport => Sport.find(29), :series => 1},
                        {:name => '400m', :sport => Sport.find(29), :series => 1},
                        {:name => '400m aidat', :sport => Sport.find(29), :series => 1},
                        {:name => '4x100m viesti', :sport => Sport.find(29), :series => 1},
                        {:name => '4x400m viesti', :sport => Sport.find(29), :series => 1},
                        {:name => '5000m ', :sport => Sport.find(29), :series => 1},
                        {:name => '50km kävely', :sport => Sport.find(29), :series => 1},
                        {:name => '800m ', :sport => Sport.find(29), :series => 1},
                        {:name => 'Kymmenottelu', :sport => Sport.find(29), :series => 1},
                        {:name => 'Kiekonheitto', :sport => Sport.find(29), :series => 1},
                        {:name => 'Moukarinheitto', :sport => Sport.find(29), :series => 1},
                        {:name => 'Korkeushyppy', :sport => Sport.find(29), :series => 1},
                        {:name => 'Keihäänheitto', :sport => Sport.find(29), :series => 1},
                        {:name => 'Maratooni', :sport => Sport.find(29), :series => 1},
                        {:name => 'Seiväshyppy', :sport => Sport.find(29), :series => 1},
                        {:name => 'Kuulantyöntö', :sport => Sport.find(29), :series => 1},
                        {:name => 'pituushyppy', :sport => Sport.find(29), :series => 1},
                        {:name => 'Kolmiloikka', :sport => Sport.find(29), :series => 1},
                        {:name => '10 000m', :sport => Sport.find(29), :series => 2},
                        {:name => '100m', :sport => Sport.find(29), :series => 2},
                        {:name => '100m aidat', :sport => Sport.find(29), :series => 2},
                        {:name => '1500m', :sport => Sport.find(29), :series => 2},
                        {:name => '200m', :sport => Sport.find(29), :series => 2},
                        {:name => '20km kävely', :sport => Sport.find(29), :series => 2},
                        {:name => '3000m estejuoksu', :sport => Sport.find(29), :series => 2},
                        {:name => '400m', :sport => Sport.find(29), :series => 2},
                        {:name => '400m aidat', :sport => Sport.find(29), :series => 2},
                        {:name => '4x100m viesti', :sport => Sport.find(29), :series => 2},
                        {:name => '4x400m viesti', :sport => Sport.find(29), :series => 2},
                        {:name => '5000m ', :sport => Sport.find(29), :series => 2},
                        {:name => '800m ', :sport => Sport.find(29), :series => 2},
                        {:name => 'Kiekonheitto', :sport => Sport.find(29), :series => 2},
                        {:name => 'Moukarinheitto', :sport => Sport.find(29), :series => 2},
                        {:name => 'Seitsenottelu', :sport => Sport.find(29), :series => 2},
                        {:name => 'Korkeushyppy', :sport => Sport.find(29), :series => 2},
                        {:name => 'Keihäänheitto', :sport => Sport.find(29), :series => 2},
                        {:name => 'pituushyppy', :sport => Sport.find(29), :series => 2},
                        {:name => 'Maratooni', :sport => Sport.find(29), :series => 2},
                        {:name => 'Korkeushyppy', :sport => Sport.find(29), :series => 2},
                        {:name => 'Kuulantyöntö', :sport => Sport.find(29), :series => 2},
                        {:name => 'Kolmiloikka', :sport => Sport.find(29), :series => 2},
                        {:name => 'Joukkue moniottelu', :sport => Sport.find(28), :series => 1},
                        {:name => 'Joukkue moniottelu', :sport => Sport.find(28), :series => 2},
                        {:name => 'Sekanelinpeli', :sport => Sport.find(23), :series => 3}

                      ])

#events = Event.create( name: 'Jalkapallo, naiset', sport: Sport.find(2), series: 2)

countries = Country.create([
                               {:name => 'Afganistan', :iso_code => 'AF'},
                               {:name => 'Albania', :iso_code => 'AL'},
                               {:name => 'Algeria', :iso_code => 'DZ'},
                               {:name => 'Amerikan Samoa', :iso_code => 'AS'},
                               {:name => 'Andorra', :iso_code => 'AD'},
                               {:name => 'Angola', :iso_code => 'AO'},
                               {:name => 'Antigua ja Barbuda', :iso_code => 'AG'},
                               {:name => 'Argentiina', :iso_code => 'AR'},
                               {:name => 'Armenia', :iso_code => 'AM'},
                               {:name => 'Australia', :iso_code => 'AU'},
                               {:name => 'Itävalta', :iso_code => 'AT'},
                               {:name => 'Azerbaidzan', :iso_code => 'AZ'},
                               {:name => 'Bahama', :iso_code => 'BS'},
                               {:name => 'Bahrain', :iso_code => 'BH'},
                               {:name => 'Barbados', :iso_code => 'BB'},
                               {:name => 'Valko-Venäjä', :iso_code => 'BY'},
                               {:name => 'Belgia', :iso_code => 'BE'},
                               {:name => 'Bermuda', :iso_code => 'BM'},
                               {:name => 'Bolivia', :iso_code => 'BO'},
                               {:name => 'Bosnia ja Hertsegovina', :iso_code => 'BA'},
                               {:name => 'Botswana', :iso_code => 'BW'},
                               {:name => 'Brasilia', :iso_code => 'BR'},
                               {:name => 'Brittiläiset Neitsytsaaret', :iso_code => 'VG'},
                               {:name => 'Bulgaria', :iso_code => 'BG'},
                               {:name => 'Burundi', :iso_code => 'BI'},
                               {:name => 'Kamerun', :iso_code => 'CM'},
                               {:name => 'Kanada', :iso_code => 'CA'},
                               {:name => 'Caymansaaret', :iso_code => 'KY'},
                               {:name => 'Keski-Afrikan tasavalta', :iso_code => 'CF'},
                               {:name => 'Chile', :iso_code => 'CL'},
                               {:name => 'Kiina', :iso_code => 'CN'},
                               {:name => 'Kolumbia', :iso_code => 'CO'},
                               {:name => 'Kongo', :iso_code => 'CG'},
                               {:name => 'Cookinsaaret', :iso_code => 'CK'},
                               {:name => 'Costa Rica', :iso_code => 'CR'},
                               {:name => 'Norsunluurannikko', :iso_code => 'CI'},
                               {:name => 'Kroatia', :iso_code => 'HR'},
                               {:name => 'Kuuba', :iso_code => 'CU'},
                               {:name => 'Kypros', :iso_code => 'CY'},
                               {:name => 'Tsekki', :iso_code => 'CZ'},
                               {:name => 'Tanska', :iso_code => 'DK'},
                               {:name => 'Djibouti', :iso_code => 'DJ'},
                               {:name => 'Dominica', :iso_code => 'DM'},
                               {:name => 'Dominikaaninen tasavalta', :iso_code => 'DO'},
                               {:name => 'Ecuador', :iso_code => 'EC'},
                               {:name => 'Egypti', :iso_code => 'EG'},
                               {:name => 'El Salvador', :iso_code => 'SV'},
                               {:name => 'Eritrea', :iso_code => 'ER'},
                               {:name => 'Viro', :iso_code => 'EE'},
                               {:name => 'Etiopia', :iso_code => 'ET'},
                               {:name => 'Fidzi', :iso_code => 'FJ'},
                               {:name => 'Suomi', :iso_code => 'FI'},
                               {:name => 'Ranska', :iso_code => 'FR'},
                               {:name => 'Gabon', :iso_code => 'GA'},
                               {:name => 'Georgia', :iso_code => 'GE'},
                               {:name => 'Saksa', :iso_code => 'DE'},
                               {:name => 'Ghana', :iso_code => 'GH'},
                               {:name => 'Iso-Britannia', :iso_code => 'GB'},
                               {:name => 'Kreikka', :iso_code => 'GR'},
                               {:name => 'Grenada', :iso_code => 'GD'},
                               {:name => 'Guatemala', :iso_code => 'GT'},
                               {:name => 'Guinea-Bissau', :iso_code => 'GW'},
                               {:name => 'Guyana', :iso_code => 'GY'},
                               {:name => 'Haiti', :iso_code => 'HT'},
                               {:name => 'Honduras', :iso_code => 'HN'},
                               {:name => 'Hongkong', :iso_code => 'HK'},
                               {:name => 'Unkari', :iso_code => 'HU'},
                               {:name => 'Islanti', :iso_code => 'IS'},
                               {:name => 'Intia', :iso_code => 'IN'},
                               {:name => 'Indonesia', :iso_code => 'ID'},
                               {:name => 'Iran', :iso_code => 'IR'},
                               {:name => 'Irlanti', :iso_code => 'IE'},
                               {:name => 'Israel', :iso_code => 'IL'},
                               {:name => 'Italia', :iso_code => 'IT'},
                               {:name => 'Jamaika', :iso_code => 'JM'},
                               {:name => 'Japani', :iso_code => 'JP'},
                               {:name => 'Jordania', :iso_code => 'JO'},
                               {:name => 'Kazakstan', :iso_code => 'KZ'},
                               {:name => 'Kenia', :iso_code => 'KE'},
                               {:name => 'Pohjois-Korea', :iso_code => 'KP'},
                               {:name => 'Etelä-Korea', :iso_code => 'KR'},
                               {:name => 'Kuwait', :iso_code => 'KW'},
                               {:name => 'Kirgisia', :iso_code => 'KG'},
                               {:name => 'Latvia', :iso_code => 'LV'},
                               {:name => 'Libanon', :iso_code => 'LB'},
                               {:name => 'Liberia', :iso_code => 'LR'},
                               {:name => 'Libya', :iso_code => 'LY'},
                               {:name => 'Liettua', :iso_code => 'LT'},
                               {:name => 'Luxemburg', :iso_code => 'LU'},
                               {:name => 'Madagaskar', :iso_code => 'MG'},
                               {:name => 'Malesia', :iso_code => 'MY'},
                               {:name => 'Malta', :iso_code => 'MT'},
                               {:name => 'Meksiko', :iso_code => 'MX'},
                               {:name => 'Moldova', :iso_code => 'MD'},
                               {:name => 'Mongolia', :iso_code => 'MN'},
                               {:name => 'Montenegro', :iso_code => 'ME'},
                               {:name => 'Marokko', :iso_code => 'MA'},
                               {:name => 'Mosambik', :iso_code => 'MZ'},
                               {:name => 'Namibia', :iso_code => 'NA'},
                               {:name => 'Hollanti', :iso_code => 'NL'},
                               {:name => 'Uusi-Seelanti', :iso_code => 'NZ'},
                               {:name => 'Nigeria', :iso_code => 'NG'},
                               {:name => 'Norja', :iso_code => 'NO'},
                               {:name => 'Oman', :iso_code => 'OM'},
                               {:name => 'Pakistan', :iso_code => 'PK'},
                               {:name => 'Panama', :iso_code => 'PA'},
                               {:name => 'Papua-Uusi-Guinea', :iso_code => 'PG'},
                               {:name => 'Paraguay', :iso_code => 'PY'},
                               {:name => 'Peru', :iso_code => 'PE'},
                               {:name => 'Filippiinit', :iso_code => 'PH'},
                               {:name => 'Puola', :iso_code => 'PL'},
                               {:name => 'Portugali', :iso_code => 'PT'},
                               {:name => 'Puerto Rico', :iso_code => 'PR'},
                               {:name => 'Qatar', :iso_code => 'QA'},
                               {:name => 'Romania', :iso_code => 'RO'},
                               {:name => 'Venäjä', :iso_code => 'RU'},
                               {:name => 'Ruanda', :iso_code => 'RW'},
                               {:name => 'Saint Kitts ja Nevis', :iso_code => 'KN'},
                               {:name => 'Saint Lucia', :iso_code => 'LC'},
                               {:name => 'Samoa', :iso_code => 'WS'},
                               {:name => 'San Marino', :iso_code => 'SM'},
                               {:name => 'Saudi-Arabia', :iso_code => 'SA'},
                               {:name => 'Senegal', :iso_code => 'SN'},
                               {:name => 'Serbia', :iso_code => 'RS'},
                               {:name => 'Sierra Leone', :iso_code => 'SL'},
                               {:name => 'Singapore', :iso_code => 'SG'},
                               {:name => 'Slovakia', :iso_code => 'SK'},
                               {:name => 'Slovenia', :iso_code => 'SI'},
                               {:name => 'Etelä-Afrikka', :iso_code => 'ZA'},
                               {:name => 'Espanja', :iso_code => 'ES'},
                               {:name => 'Sudan', :iso_code => 'SD'},
                               {:name => 'Ruotsi', :iso_code => 'SE'},
                               {:name => 'Sveitsi', :iso_code => 'CH'},
                               {:name => 'Syyria', :iso_code => 'SY'},
                               {:name => 'Kiinan Taipei', :iso_code => 'TW'},
                               {:name => 'Tadzikistan', :iso_code => 'TJ'},
                               {:name => 'Tansania', :iso_code => 'TZ'},
                               {:name => 'Thaimaa', :iso_code => 'TH'},
                               {:name => 'Trinidad ja Tobago', :iso_code => 'TT'},
                               {:name => 'Tunisia', :iso_code => 'TN'},
                               {:name => 'Turkki', :iso_code => 'TR'},
                               {:name => 'Turkmenistan', :iso_code => 'TM'},
                               {:name => 'Uganda', :iso_code => 'UG'},
                               {:name => 'Ukraina', :iso_code => 'UA'},
                               {:name => 'Yhdistyneet arabiemiirikunnat', :iso_code => 'AE'},
                               {:name => 'Yhdysvallat', :iso_code => 'US'},
                               {:name => 'Uruguay', :iso_code => 'UY'},
                               {:name => 'Uzbekistan', :iso_code => 'UZ'},
                               {:name => 'Venezuela', :iso_code => 'VE'},
                               {:name => 'Vietnam', :iso_code => 'VN'},
                               {:name => 'Neitsytsaaret', :iso_code => 'VI'},
                               {:name => 'Sambia', :iso_code => 'ZM'},
                               {:name => 'Zimbabwe', :iso_code => 'ZW'}
                           ])
